apiVersion: apps/v1
kind: Deployment
metadata:
  name: testappsettings-webapi-deployment
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: testappsettings
          image: akasharya3/testappsettings:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80;http://+:443
            - name: TestRoot__Test.Value
              value: "Kubernetes"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP