apiVersion: v1
kind: Service
metadata:
  name: testappsettings-webapi-service
spec:
  type: LoadBalancer
  selector:
    app: webapi
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
    - port: 8443
      targetPort: 443
      protocol: TCP
      name: https