apiVersion: v1
kind: Service
metadata:
  name: webapi
spec:
  type: NodePort
  selector:
    service: webapi
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      nodePort: 30008
      protocol: TCP
      name: https